// This file is auto-generated by @hey-api/openapi-ts

export type AuthorCreate = {
    name: string;
};

export type AuthorPublic = {
    name: string;
    id: number;
    owner_id?: (string | null);
    books_count?: (number | null);
    created_at?: (string | null);
};

export type AuthorsPublic = {
    data: Array<AuthorPublic>;
    count: number;
    page?: (number | null);
    limit?: (number | null);
    total?: (number | null);
    total_pages?: (number | null);
};

export type AuthorUpdate = {
    name?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BookCreate = {
    title: string;
    author_id: number;
};

export type BookPublic = {
    title: string;
    id: number;
    author_id: number;
    owner_id?: (string | null);
    author_name?: (string | null);
    created_at?: (string | null);
};

export type BooksPublic = {
    data: Array<BookPublic>;
    count: number;
    page?: (number | null);
    limit?: (number | null);
    total?: (number | null);
    total_pages?: (number | null);
};

export type BookUpdate = {
    title?: (string | null);
    author_id?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReviewCreate = {
    content: string;
    book_id: number;
};

export type ReviewPublic = {
    content: string;
    id: number;
    book_id: number;
    owner_id?: (string | null);
    book_title?: (string | null);
    author_name?: (string | null);
    created_at?: (string | null);
};

export type ReviewsPublic = {
    data: Array<ReviewPublic>;
    count: number;
    page?: (number | null);
    limit?: (number | null);
    total?: (number | null);
    total_pages?: (number | null);
};

export type ReviewUpdate = {
    book_id?: (number | null);
    content?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthorsReadAuthorsData = {
    page?: number;
    pageSize?: number;
};

export type AuthorsReadAuthorsResponse = (AuthorsPublic);

export type AuthorsCreateAuthorData = {
    requestBody: AuthorCreate;
};

export type AuthorsCreateAuthorResponse = (AuthorPublic);

export type AuthorsReadAuthorData = {
    id: number;
};

export type AuthorsReadAuthorResponse = (AuthorPublic);

export type AuthorsUpdateAuthorData = {
    id: number;
    requestBody: AuthorUpdate;
};

export type AuthorsUpdateAuthorResponse = (AuthorPublic);

export type AuthorsDeleteAuthorData = {
    id: number;
};

export type AuthorsDeleteAuthorResponse = (Message);

export type BooksReadBooksData = {
    page?: number;
    pageSize?: number;
};

export type BooksReadBooksResponse = (BooksPublic);

export type BooksCreateBookData = {
    requestBody: BookCreate;
};

export type BooksCreateBookResponse = (BookPublic);

export type BooksReadBookData = {
    id: number;
};

export type BooksReadBookResponse = (BookPublic);

export type BooksUpdateBookData = {
    id: number;
    requestBody: BookUpdate;
};

export type BooksUpdateBookResponse = (BookPublic);

export type BooksDeleteBookData = {
    id: number;
};

export type BooksDeleteBookResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ReviewsReadReviewsData = {
    page?: number;
    pageSize?: number;
};

export type ReviewsReadReviewsResponse = (ReviewsPublic);

export type ReviewsCreateReviewData = {
    requestBody: ReviewCreate;
};

export type ReviewsCreateReviewResponse = (ReviewPublic);

export type ReviewsReadReviewData = {
    id: number;
};

export type ReviewsReadReviewResponse = (ReviewPublic);

export type ReviewsUpdateReviewData = {
    id: number;
    requestBody: ReviewUpdate;
};

export type ReviewsUpdateReviewResponse = (ReviewPublic);

export type ReviewsDeleteReviewData = {
    id: number;
};

export type ReviewsDeleteReviewResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);