/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutReviewsIndexRouteImport } from './routes/_layout/reviews/index'
import { Route as LayoutBooksIndexRouteImport } from './routes/_layout/books/index'
import { Route as LayoutAuthorsIndexRouteImport } from './routes/_layout/authors/index'
import { Route as LayoutReviewsCreateRouteImport } from './routes/_layout/reviews/create'
import { Route as LayoutBooksCreateRouteImport } from './routes/_layout/books/create'
import { Route as LayoutAuthorsCreateRouteImport } from './routes/_layout/authors/create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewsIndexRoute = LayoutReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBooksIndexRoute = LayoutBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthorsIndexRoute = LayoutAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewsCreateRoute = LayoutReviewsCreateRouteImport.update({
  id: '/reviews/create',
  path: '/reviews/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBooksCreateRoute = LayoutBooksCreateRouteImport.update({
  id: '/books/create',
  path: '/books/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthorsCreateRoute = LayoutAuthorsCreateRouteImport.update({
  id: '/authors/create',
  path: '/authors/create',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/authors/create': typeof LayoutAuthorsCreateRoute
  '/books/create': typeof LayoutBooksCreateRoute
  '/reviews/create': typeof LayoutReviewsCreateRoute
  '/authors/': typeof LayoutAuthorsIndexRoute
  '/books/': typeof LayoutBooksIndexRoute
  '/reviews/': typeof LayoutReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/authors/create': typeof LayoutAuthorsCreateRoute
  '/books/create': typeof LayoutBooksCreateRoute
  '/reviews/create': typeof LayoutReviewsCreateRoute
  '/authors': typeof LayoutAuthorsIndexRoute
  '/books': typeof LayoutBooksIndexRoute
  '/reviews': typeof LayoutReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/authors/create': typeof LayoutAuthorsCreateRoute
  '/_layout/books/create': typeof LayoutBooksCreateRoute
  '/_layout/reviews/create': typeof LayoutReviewsCreateRoute
  '/_layout/authors/': typeof LayoutAuthorsIndexRoute
  '/_layout/books/': typeof LayoutBooksIndexRoute
  '/_layout/reviews/': typeof LayoutReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/authors/create'
    | '/books/create'
    | '/reviews/create'
    | '/authors/'
    | '/books/'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/authors/create'
    | '/books/create'
    | '/reviews/create'
    | '/authors'
    | '/books'
    | '/reviews'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/authors/create'
    | '/_layout/books/create'
    | '/_layout/reviews/create'
    | '/_layout/authors/'
    | '/_layout/books/'
    | '/_layout/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reviews/': {
      id: '/_layout/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof LayoutReviewsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/books/': {
      id: '/_layout/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof LayoutBooksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/authors/': {
      id: '/_layout/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof LayoutAuthorsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reviews/create': {
      id: '/_layout/reviews/create'
      path: '/reviews/create'
      fullPath: '/reviews/create'
      preLoaderRoute: typeof LayoutReviewsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/books/create': {
      id: '/_layout/books/create'
      path: '/books/create'
      fullPath: '/books/create'
      preLoaderRoute: typeof LayoutBooksCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/authors/create': {
      id: '/_layout/authors/create'
      path: '/authors/create'
      fullPath: '/authors/create'
      preLoaderRoute: typeof LayoutAuthorsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAuthorsCreateRoute: typeof LayoutAuthorsCreateRoute
  LayoutBooksCreateRoute: typeof LayoutBooksCreateRoute
  LayoutReviewsCreateRoute: typeof LayoutReviewsCreateRoute
  LayoutAuthorsIndexRoute: typeof LayoutAuthorsIndexRoute
  LayoutBooksIndexRoute: typeof LayoutBooksIndexRoute
  LayoutReviewsIndexRoute: typeof LayoutReviewsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAuthorsCreateRoute: LayoutAuthorsCreateRoute,
  LayoutBooksCreateRoute: LayoutBooksCreateRoute,
  LayoutReviewsCreateRoute: LayoutReviewsCreateRoute,
  LayoutAuthorsIndexRoute: LayoutAuthorsIndexRoute,
  LayoutBooksIndexRoute: LayoutBooksIndexRoute,
  LayoutReviewsIndexRoute: LayoutReviewsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
